<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="coverlet.collector"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.TimeZones\RapidStreamer.Channels.TimeZones.csproj" />
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.Chat\RapidStreamer.Channels.Chat.csproj" />
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.Clock\RapidStreamer.Channels.Clock.csproj" />
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.NetworkMonitoring\RapidStreamer.Channels.NetworkMonitoring.csproj" />
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.Notifications\RapidStreamer.Channels.Notifications.csproj" />
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.ResourceMonitoring\RapidStreamer.Channels.ResourceMonitoring.csproj" />
        <ProjectReference Include="..\..\..\src\Channels\RapidStreamer.Channels.Throughput\RapidStreamer.Channels.Throughput.csproj" />
        <ProjectReference Include="..\..\..\src\Demo\RapidStreamer.Channels.Demo.Airport\RapidStreamer.Channels.Demo.Airport.csproj" />
        <ProjectReference Include="..\..\..\src\Demo\RapidStreamer.Channels.Demo.Portfolio\RapidStreamer.Channels.Demo.Portfolio.csproj" />
        <ProjectReference Include="..\..\..\src\Demo\RapidStreamer.Channels.Demo.StockListBasic\RapidStreamer.Channels.Demo.StockListBasic.csproj" />
        <ProjectReference Include="..\..\..\src\Games\RapidStreamer.Channels.Games.RockPaperScissors\RapidStreamer.Channels.Games.RockPaperScissors.csproj" />
        <ProjectReference Include="..\..\..\src\Games\RapidStreamer.Channels.Games.TicTacToe\RapidStreamer.Channels.Games.TicTacToe.csproj" />
    </ItemGroup>

</Project>

