<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(RapidStreamerPackageId)"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="ChatChannelFeederMessage.cs">
            <DependentUpon>ChatChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="ChatChannelMetadata.cs">
            <DependentUpon>ChatChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="ChatChannelConfiguration.cs">
            <DependentUpon>ChatChannel.cs</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Pipelines\Messages\"/>
    </ItemGroup>

</Project>
