<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(ThunderPropagatorPackageId)"/>
        <PackageReference Include="Bogus"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="PortfolioDemoChannelFeederMessage.cs">
            <DependentUpon>PortfolioDemoChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="PortfolioDemoChannelMetadata.cs">
            <DependentUpon>PortfolioDemoChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="PortfolioDemoChannelConfiguration.cs">
            <DependentUpon>PortfolioDemoChannel.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
