<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(ThunderPropagatorPackageId)"/>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="NodaTime"/>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis"/>
        <PackageReference Include="Microsoft.Extensions.Http.Polly"/>
    </ItemGroup>

</Project>
