// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThunderPropagator.Channels.Games.RockPaperScissors.EntityFrameworkCore.Context;

#nullable disable

namespace ThunderPropagator.Channels.Games.RockPaperScissors.EntityFrameworkCore.UnitTests.Migrations
{
    [DbContext(typeof(RockPaperScissorsDbContext))]
    partial class RockPaperScissorsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ThunderPropagator.Channels.Games.RockPaperScissors.Models.RockPaperScissorsGameSessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstPlayerConnectionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstPlayerMove")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstPlayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstPlayerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondPlayerConnectionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondPlayerMove")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondPlayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondPlayerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("RockPaperScissorsGameSessionRecords", (string)null);
                });

            modelBuilder.Entity("ThunderPropagator.Channels.Games.RockPaperScissors.Models.RockPaperScissorsMatchReservation", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId");

                    b.ToTable("RockPaperScissorsMatchReservations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
