<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <PropertyGroup Label="PackageId">
        <PackageId Condition="'$(Configuration)' == 'Debug' And '$(Platform)' != 'AnyCPU'">$(RootNameSpace).Debug.$(Platform)</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'AnyCPU'">$(RootNameSpace).Debug</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Release' And '$(Platform)' != 'AnyCPU'">$(RootNameSpace).$(Platform)</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Release' And '$(Platform)' == 'AnyCPU'">$(RootNameSpace)</PackageId>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="RapidStreamer.Debug.ARM64" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'ARM64'"/>
        <PackageReference Include="RapidStreamer.Debug.x86" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'x86'"/>
        <PackageReference Include="RapidStreamer.Debug.x64" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'x64'"/>
        <PackageReference Include="RapidStreamer.Debug" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'AnyCPU'" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="RapidStreamer.ARM64" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'ARM64'"/>
        <PackageReference Include="RapidStreamer.x86" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'x86'"/>
        <PackageReference Include="RapidStreamer.x64" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'x64'"/>
        <PackageReference Include="RapidStreamer" Version="1.0.166-beta.4" Condition="'$(Platform)' == 'AnyCPU'"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" Version="35.6.4" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="StockListBasicDemoChannelFeederMessage.cs">
            <DependentUpon>StockListBasicDemoChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="StockListBasicDemoChannelMetadata.cs">
            <DependentUpon>StockListBasicDemoChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="StockListBasicDemoChannelFeederConfiguration.cs">
            <DependentUpon>StockListBasicDemoChannelFeeder.cs</DependentUpon>
        </Compile>
        <Compile Update="StockListBasicDemoChannelConfiguration.cs">
            <DependentUpon>StockListBasicDemoChannel.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
