using System.Runtime.CompilerServices;
using Bogus;
using RapidStreamer.Application.Feeders;

namespace RapidStreamer.Channels.Demo.Airport
{
    internal
#if !DEBUG
        sealed
#endif
        class AirportDemoChannelFeeder : IterativeFeeder<AirportDemoChannel, AirportDemoChannelFeederMessage, AirportDemoChannelFeederConfiguration>
    {
        private static readonly string[] Airports =
        [
            "Adelaide (ADL)",
            "Brisbane (BNE)",
            "Cairns (CNS)",
            "Darwin (DRW)",
            "Gold Coast (OOL)",
            "Melbourne (MEL)",
            "Perth (PER)",
            "Sydney (SYD)",
            "Dhaka (DAC)",
            "Phnom Penh (PNH)",
            "Ahmedabad (AMD)",
            "Bangalore (BLR)",
            "Calicut (CCJ)",
            "Chennai (MAA)",
            "Delhi (DEL)",
            "Goa (GOX)",
            "Hyderabad (HYD)",
            "Jaipur (JAI)",
            "Kolkata (CCU)",
            "Mumbai (BOM)",
            "Trivandrum (TRV)",
            "Denpasar (DPS)",
            "Jakarta (CGK)",
            "Chubu (NGO)",
            "Fukuoka (FUK)",
            "Haneda (HND)",
            "New Chitose Airport (CTS)",
            "Osaka-Kansai (KIX)",
            "Tokyo-Narita (NRT)",
            "Kota Kinabalu (BKI)",
            "Kuala Lumpur (KUL)",
            "Kuchung (KCH)",
            "Langkawi (LGK)",
            "Penang (PEN)",
            "Senai (JHB)",
            "Auckland (AKL)",
            "Christchurch (CHC)",
            "Queenstown (ZQN)",
            "Wellington (WLG)",
            "Islamabad (ISB)",
            "Karachi (KHI)",
            "Lahore (LHE)",
            "Peshawar (PEW)",
            "Port Moresby (POM)",
            "Manila (MNL)",
            "Incheon (ICN)",
            "Jeju International Airport (CJU)",
            "Seoul (GMP)",
            "Male (MLE)",
            "Changi (SIN)",
            "Colombo (CMB)",
            "Chiang Mai (CNX)",
            "Chiang Rai International Airport (CEI)",
            "Don Mueang (DMK)",
            "Hat Yai (HDY)",
            "Krabi (KBV)",
            "Phuket (HKT)",
            "Ko Samui  (USM)",
            "Suvarnabhumi (BKK)",
            "Utapao (UTP)",
            "Hanoi (HAN)",
            "Ho Chi Minh (SGN)",
            "Graz (GRZ)",
            "Innsbruck (INN)",
            "Klagenfurt (KLU)",
            "Linz (LNZ)",
            "Salzburg (SZG)",
            "Vienna (VIE)",
            "Brussels (BRU)",
            "Brussels South Charleroi (CRL)",
            "Sofia (SOF)",
            "Dubrovnik (DBV)",
            "Pula (PUY)",
            "Split (SPU)",
            "Zadar (ZAD)",
            "Zagreb International Airport (ZAG)",
            "Larnaca (LCA)",
            "Paphos (PFO)",
            "Prague (PRG)",
            "Billund (BLL)",
            "Copenhagen (CPH)",
            "Vágar (FAE)",
            "Helsinki (HEL)",
            "Kittilä (KTT)",
            "Rovaniemi (RVN)",
            "Annecy (NCY)",
            "Basel-Mulhouse-Freiburg (BSL/MLH)",
            "Chambery (CMF)",
            "Figari (FSC)",
            "Lyon (LYS)",
            "Nantes (NTE)",
            "Nice (NCE)",
            "Paris Beauvais-Tille Airport (BVA)",
            "Paris-Ch. De Gaulle (CDG)",
            "Paris-Orly (ORY)",
            "Berlin - Schonefeld (BER)",
            "Bremen (BRE)",
            "Cologne (CGN)",
            "Dresden (DRS)",
            "Duesseldorf (DUS)",
            "Erfut (ERF)",
            "Frankfurt (FRA)",
            "Hamburg (HAM)",
            "Hannover (HAJ)",
            "Leipzig (LEJ)",
            "Memmingen (FMM)",
            "Muenster (FMO)",
            "Munich (MUC)",
            "Nuremberg (NUE)",
            "Saarbruecken (SCN)",
            "Stuttgart (STR)",
            "Aktion (PVK)",
            "Athens (ATH)",
            "Chania (CHQ)",
            "Chios (JKH)",
            "Corfu (CFU)",
            "Heraklion (HER)",
            "Kalamata (KLX)",
            "Karpathos (AOK)",
            "Kefallinia (EFL)",
            "Kithira (KIT)",
            "Kos (KGS)",
            "Lemnos (LXS)",
            "Mikonos (JMK)",
            "Paros (PAS)",
            "Patras (GPA)",
            "Rhodes (RHO)",
            "Siteia (JSH)",
            "Skiathos (JSI)",
            "Thessalonika (SKG)",
            "Thira (JTR)",
            "Volos (VOL)",
            "Zakinthos (ZTH)",
            "Ilulissat Airport (JAV)",
            "Kangerlussuaq Airport (SFJ)",
            "Nuuk Airport (GOH)",
            "Budapest (BUD)",
            "Akureyri (AEY)",
            "Egilsstadir (EGS)",
            "Keflavik (KEF)",
            "Dublin (DUB)",
            "Eilat (ETM)",
            "Tel Aviv (TLV)",
            "Alghero (AHO)",
            "Bari (BRI)",
            "Bologna (BLQ)",
            "Brindisi (BDS)",
            "Cagliari (CAG)",
            "Catania (CTA)",
            "Florence (FLR)",
            "Genova Cristoforo Colombo (GOA)",
            "Lamezia Terme (SUF)",
            "Lampedusa (LMP)",
            "Milan - Linate (LIN)",
            "Milan - Malpensa (MXP)",
            "Milan - Orio al Serio (BGY)",
            "Naples (NAP)",
            "Olbia Costa Smeralda (OLB)",
            "Palermo (PMO)",
            "Pantelleria (PNL)",
            "Pisa (PSA)",
            "Rimini Federico Fellini (RMI)",
            "Rome - Ciampino (CIA)",
            "Rome - Fiumicino (FCO)",
            "Treviso (TSF)",
            "Turin (TRN)",
            "Venice (VCE)",
            "Verona (VRN)",
            "Jersey (JER)",
            "Pristina (PRN)",
            "Riga (RIX)",
            "Vilnius (VNO)",
            "Luxembourg (LUX)",
            "Luqa (MLA)",
            "Amsterdam (AMS)",
            "Eindhoven (EIN)",
            "Rotterdam (RTM)",
            "Skopje (SKP)",
            "Ålesund (AES)",
            "Alta (ALF)",
            "Bergen (BGO)",
            "Bodø (BOO)",
            "Harstad-Narvik (EVE)",
            "Haugesund (HAU)",
            "Kirkenes (KKN)",
            "Kristiansund (KSU)",
            "Kristiandsand (KRS)",
            "Molde (MOL)",
            "Oslo-Gardermoen (OSL)",
            "Stavanger (SVG)",
            "Svalbard (LYR)",
            "Torp (TRF)",
            "Tromsø (TOS)",
            "Trondheim (TRD)",
            "Krakow (KRK)",
            "Poznan   (POZ)",
            "Warsaw Chopina (WAW)",
            "Faro (FAO)",
            "Funchal (FNC)",
            "Lisbon (LIS)",
            "Ponta Delgada (PDL)",
            "Porto (OPO)",
            "Moscow-Domodedovo (DME)",
            "Moscow-Sheremetyevo (SVO)",
            "Moscow-Vnukovo (VKO)",
            "St. Petersburg (LED)",
            "Bratislava (BTS)",
            "Ljubljana (LJU)",
            "Alicante (ALC)",
            "Almeria (LEI)",
            "Asturias (OVD)",
            "Barcelona (BCN)",
            "Bilbao (BIO)",
            "Corvera (RMU)",
            "Fuerteventura (FUE)",
            "Gerona (GRO)",
            "Gran Canaria (LPA)",
            "Granada (GRX)",
            "Ibiza (IBZ)",
            "Jerez (XRY)",
            "La Coruna (LCG)",
            "La Palma (SPC)",
            "Lanzarote (ACE)",
            "Madrid Barajas (MAD)",
            "Malaga (AGP)",
            "Menorca (MAH)",
            "Palma Mallorca (PMI)",
            "Pamplona (PNA)",
            "Reus (REU)",
            "San Sebastian (EAS)",
            "Santander (SDR)",
            "Seville (SVQ)",
            "Tenerife - Norte (TFN)",
            "Tenerife - Sur (TFS)",
            "Valencia (VLC)",
            "Ängelholm Helsingborg (AGH)",
            "Åre Östersund (OSD)",
            "Arvidsjaur (AJR)",
            "Gothenburg (GOT)",
            "Kiruna (KRN)",
            "Ronneby Airport (RNB)",
            "Skellefteå (SFT)",
            "Stockholm-Arlanda (ARN)",
            "Stockholm-Bromma (BMA)",
            "Visby Airport Swedavia (VBY)",
            "Geneva (GVA)",
            "Zurich (ZRH)",
            "Ankara (ESB)",
            "Antalya (AYT)",
            "Ataturk (ISL)",
            "Bodrum (BJV)",
            "Dalaman (DLM)",
            "Istanbul (IST)",
            "Istanbul Sabiha Gökçen (SAW)",
            "Izmir (ADB)",
            "Kyiv (KBP)",
            "Zhuliany (IEV)",
            "Aberdeen (ABZ)",
            "Belfast- Belfast City (BHD)",
            "Belfast- Belfast International (BFS)",
            "Birmingham (BHX)",
            "Bristol (BRS)",
            "East Midlands (EMA)",
            "Edinburgh (EDI)",
            "Glasgow (GLA)",
            "Leeds Bradford (LBA)",
            "Liverpool (LPL)",
            "London-City (LCY)",
            "London-Gatwick (LGW)",
            "London-Heathrow (LHR)",
            "London-Luton (LTN)",
            "Manchester (MAN)",
            "Newcastle (NCL)",
            "Southampton (SOU)",
            "Stansted (STN)",
            "Bahrain (BAH)",
            "Borg El Arab (HBE)",
            "Cairo (CAI)",
            "Hurghada (HRG )",
            "Marsa Alam (RMF)",
            "Sharm El Sheikh (SSH)",
            "Sohag (HMB)",
            "Accra (ACC)",
            "Kuwait (KWI)",
            "Casablanca (CMN)",
            "Marrakech (RAK)",
            "Rabat Salé (RBA)",
            "Doha (DIA)",
            "Doha (DOH)",
            "Aeroporto Internacional Amilcar Cabral (SID)",
            "Aeroporto Internacional Aristides Pereira (BVC)",
            "Aeroporto Internacional Nelson Mandela (RAI)",
            "Abha (AHB)",
            "Al-Ahsa (HOF)",
            "Arar (RAE)",
            "Buraydah (ELQ)",
            "Dammam (DMM)",
            "Ha'il (HAS)",
            "Jeddah (JED)",
            "Jizan (GIZ)",
            "Medina (MED)",
            "Neom Bay (NUM)",
            "Riyadh (RUH)",
            "Sakakah (AJF)",
            "Tabuk (TUU)",
            "Ta'if (TIF)",
            "Yanbu (YNB)",
            "Seychelles (SEZ)",
            "Cape Town (CPT)",
            "Durban (DUR)",
            "Johannesburg (JNB)",
            "Muscat International (MCT)",
            "Monastir (MIR)",
            "Tunis-Carthage (TUN)",
            "Abu Dhabi (AUH)",
            "Dubai Al Maktoum International (DWC)",
            "Dubai International (DXB)",
            "Beijing Capital (PEK)",
            "Beijing Daxing (PKX)",
            "Changchun (CGQ)",
            "Changsha Huanghua (CSX)",
            "Chengdu Shuangliu (CTU)",
            "Chengdu Tianfu (TFU)",
            "Chongqing Jiangbei (CKG)",
            "Dalian Zhoushuizi (DLC)",
            "Fuzhou Changle (FOC)",
            "Guangzhou Baiyun (CAN)",
            "Guiyang (KWE)",
            "Haikou Meilan (HAK)",
            "Hangzhou Xiaoshan (HGH)",
            "Harbin (HRB)",
            "Hohhot (HET)",
            "Hulun Buir (HLD)",
            "Jinan (TNA)",
            "Kunming Changshui (KMG)",
            "Lanzhou (LHW)",
            "Nanchang (KHN)",
            "Nanjing Lukou (NKG)",
            "Nanning (NNG)",
            "Qingdao Liuting (TAO)",
            "Sanya Fenghuang (SYX)",
            "Shanghai Hongqiao (SHA)",
            "Shanghai Pudong (PVG)",
            "Shenyang (SHE)",
            "Shenzhen Bao'an (SZX)",
            "Shijiazhuang (SJW)",
            "Tianjin Binhai (TSN)",
            "Taiyuan (TYN)",
            "Urumchi Diwopu (URC)",
            "Wuhan Tianhe (WUH)",
            "Xi’an Xianyang (XIY)",
            "Xiamen Gaoqi (XMN)",
            "Zhengzhou (CGO)",
            "Zhuhai (ZUH)",
            "Kaohsiung (KHH)",
            "Taipei (TPE)",
            "Hong Kong (HKG)",
            "Macau (MFM)",
            "Bermuda (BDA)",
            "Aeroporto Internacional De Brasília (BSB)",
            "Aeroporto Internacional De Campinas - Viracopos (VCP)",
            "Aeroporto Internacional Tancredo Neves (CNF)",
            "Florianopolis (FLN)",
            "Fortaleza (FOR)",
            "Porto Alegre (POA)",
            "Recife (REC)",
            "Rio de Janeiro (GIG)",
            "Rio de Janeiro (SDU)",
            "Salvador (SSA)",
            "Sao Paulo (GRU)",
            "Sao Paulo (CGH)",
            "Pampulha (PLU)",
            "Calgary (YYC)",
            "Montreal (YUL)",
            "Quebec (YQB)",
            "Toronto (YTZ)",
            "Toronto (YYZ)",
            "Vancouver (YVR)",
            "Grand Cayman (GCM)",
            "Bogota (BOG)",
            "Havana (HAV)",
            "Holguin (HOG)",
            "Santa Clara (SNU)",
            "Varadero (VRA)",
            "Santo Domingo (SDQ)",
            "Mexico City (MEX)",
            "Lima (LIM)",
            "Providenciales International Airport (PLS)",
            "Chicago-O' Hare (ORD)",
            "Los Angeles (LAX)",
            "New York-J.F. Kennedy (JFK)",
            "Newark (EWR)",
            "Orlando (MCO)",
            "San Francisco (SFO)",
            "Seattle-Tacoma International Airport (SEA)"
        ];

        private static readonly string[] Statuses =
        [
            "Scheduled - On-time", //0
            "Scheduled - Delayed", //1
            "En Route - On-time", //2
            "En Route - Delayed", //3
            "Landed - On-time", //4
            "Landed - Delayed", //5
            "Cancelled", //6
            "Deleted" //7
        ];

        private readonly HashSet<AirportDemoChannelFeederMessage> _airports;

        public AirportDemoChannelFeeder(AirportDemoChannel channel,
            AirportDemoChannelFeederConfiguration feederConfiguration,
            IFeederHandler<AirportDemoChannel, AirportDemoChannelFeederMessage> feederHandler,
            IServiceProvider serviceProvider)
            : base(channel, feederConfiguration, feederHandler, serviceProvider)
        {
            _airports = GenerateAirports(DateTime.UtcNow.TimeOfDay.Hours);
        }

        private static HashSet<AirportDemoChannelFeederMessage> GenerateAirports(int minHour = 0)
            => new Faker<AirportDemoChannelFeederMessage>()
                .RuleFor(x => x.Key, AirportDemoChannelMetadata.AirportDemo)
                .RuleFor(x => x.Destination, faker => faker.PickRandom(Airports))
                .RuleFor(x => x.Departure, faker => new TimeSpan(faker.Random.Int(minHour, 23), faker.Random.Int(0, 59), 0))
                .RuleFor(x => x.Flight, faker => $"RS{faker.UniqueIndex}{faker.Random.Int(10, 999)}")
                .RuleFor(x => x.Airline, $"({nameof(RapidStreamer)} Airlines) RSAL")
                .RuleFor(x => x.Terminal, faker => faker.Random.Int(1, 8))
                .RuleFor(x => x.Status, (faker, message) => message.Departure < DateTime.Now.TimeOfDay ? faker.PickRandom(Statuses[4..]) : Statuses[0])
                .Generate(Random.Shared.Next(10, Airports.Length))
                .ToHashSet();

        protected override async IAsyncEnumerable<FeederReceivedMessage<AirportDemoChannelFeederMessage>> ReceiveAsync(
            [EnumeratorCancellation] CancellationToken cancellationToken = default)
        {
            await Task.Delay(TimeSpan.FromSeconds(10), cancellationToken);

            var toRemoveAirports = _airports
                .Where(airport => airport.Departure < DateTime.UtcNow.AddMinutes(-30).TimeOfDay)
                .ToArray();

            if (toRemoveAirports.Length > 0)
            {
                foreach (var airport in toRemoveAirports)
                {
                    airport.IsDeleted = true;
                    _airports.Remove(airport);
                    yield return airport;
                }

                var newAirports = GenerateAirports(DateTime.Now.TimeOfDay.Hours);
                foreach (var airport in newAirports)
                    _airports.Add(airport);
            }

            var faker = new Faker();
            foreach (var airport in _airports)
            {
                if (airport.Status == Statuses[6] || airport.Status == Statuses[7])
                    continue;

                var flag = faker.Random.Int(1, 10);
                var cancelFlags = Enumerable.Range(1, 5).Select(_ => faker.Random.Bool()).All(x => x);
                var deleteFlags = Enumerable.Range(1, 5).Select(_ => faker.Random.Bool()).All(x => x);

                if (deleteFlags)
                    airport.Status = Statuses[7];
                else if (cancelFlags)
                    airport.Status = Statuses[6];
                else if (flag == 7)
                {
                    airport.Status = Statuses[1];
                    airport.Departure = airport.Departure.Add(new TimeSpan(faker.Random.Long(900_000_000, 14_400_000_000)));
                }

                yield return airport;
            }
        }
    }
}