// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThunderPropagator.Channels.Games.TicTacToe.EntityFrameworkCore.Context;

#nullable disable

namespace ThunderPropagator.Channels.Games.TicTacToe.EntityFrameworkCore.UnitTests.Migrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    partial class TicTacToeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ThunderPropagator.Channels.Games.TicTacToe.Models.TicTacToeGameRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentTurnSign")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player1ConnectionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Player1Sign")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player2ConnectionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Player2DifficultyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Player2Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player2Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.ToTable("TicTacToeGames", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
