<#
.SYNOPSIS
    Generates the local media fixtures used by this repo's opt-in FFmpeg integration tests (#237).

.DESCRIPTION
    Every fixture here is 100% synthetically generated by FFmpeg's own built-in "lavfi" source
    filters (testsrc2 for video, sine for audio) — no external video/audio content of any kind is
    downloaded, recorded, or embedded. That makes provenance and license trivial: the output belongs
    entirely to whoever runs this script, exactly like any other FFmpeg-generated test pattern. See
    README.md in this same folder for the full provenance/license note and for which opt-in test
    classes consume each fixture's own environment variable.

    Requires the `ffmpeg` CLI on PATH (any recent build with libx264/libaac and the lavfi source
    filters enabled — the default build on most package managers, e.g. `apt install ffmpeg`,
    `brew install ffmpeg`, or the Windows builds from https://ffmpeg.org/download.html).

.PARAMETER OutputDirectory
    Where to write the generated files. Defaults to a `generated/` subfolder next to this script,
    which is .gitignore'd — see this repo's own .gitignore entry for #237.

.EXAMPLE
    ./Generate-VideoPlayerFixtures.ps1
    Then point the opt-in tests at the results, e.g. (PowerShell):
        $env:THUNDERPROPAGATOR_VIDEOPLAYER_CFR_FIXTURE = (Resolve-Path ./generated/cfr-fixture.mp4)
        $env:THUNDERPROPAGATOR_VIDEOPLAYER_VFR_FIXTURE = (Resolve-Path ./generated/vfr-fixture.mp4)
        $env:THUNDERPROPAGATOR_VIDEOPLAYER_AV_FIXTURE   = (Resolve-Path ./generated/cfr-fixture.mp4)
    dotnet test --filter "FullyQualifiedName~Fixture"
#>
[CmdletBinding()]
param(
    [string]$OutputDirectory = (Join-Path $PSScriptRoot "generated")
)

$ErrorActionPreference = "Stop"

if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
    throw "ffmpeg was not found on PATH. Install it (e.g. 'apt install ffmpeg', 'brew install ffmpeg', or https://ffmpeg.org/download.html) and re-run this script."
}

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

# ---------------------------------------------------------------------------
# CFR fixture: exactly 25fps, 2 seconds (50 frames), 320x240, plus a synthetic
# 440Hz sine-wave audio track (mono, 44.1kHz) — also reusable as the
# AudioVideoSyncFixtureTests fixture (THUNDERPROPAGATOR_VIDEOPLAYER_AV_FIXTURE),
# since it carries both tracks.
# ---------------------------------------------------------------------------
$cfrPath = Join-Path $OutputDirectory "cfr-fixture.mp4"
Write-Host "Generating CFR fixture: $cfrPath"
& ffmpeg -y -f lavfi -i "testsrc2=size=320x240:rate=25:duration=2" `
    -f lavfi -i "sine=frequency=440:duration=2" `
    -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest $cfrPath
if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed generating the CFR fixture (exit code $LASTEXITCODE)." }

# ---------------------------------------------------------------------------
# VFR fixture: a 60fps synthetic source thinned to irregular intervals via
# FFmpeg's own documented "select frames at random intervals" idiom (see the
# `select` filter's manual: https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect)
# combined with -vsync vfr so the container keeps each frame's own irregular
# PTS instead of resampling to a constant rate. Video-only — VFR is a
# video-timeline property; this fixture has no audio track.
#
# NOTE: `random()`'s own output depends on FFmpeg's build, so re-running this
# script can produce a slightly different frame count/timing each time. That's
# fine for what the opt-in tests actually assert (IsVariableFrameRate is true,
# durations vary, PTS stays non-decreasing) — none of them hard-code an exact
# frame count for this fixture. Verify locally with `ffprobe -show_frames` if
# you want to see the actual generated timestamps.
# ---------------------------------------------------------------------------
$vfrPath = Join-Path $OutputDirectory "vfr-fixture.mp4"
Write-Host "Generating VFR fixture: $vfrPath"
& ffmpeg -y -f lavfi -i "testsrc2=size=320x240:rate=60:duration=2" `
    -vf "select=isnan(prev_selected_t)+gt(t-prev_selected_t\,random(0)*0.08+0.02)" `
    -vsync vfr -c:v libx264 -pix_fmt yuv420p $vfrPath
if ($LASTEXITCODE -ne 0) { throw "ffmpeg failed generating the VFR fixture (exit code $LASTEXITCODE)." }

Write-Host ""
Write-Host "Done. Generated fixtures in $OutputDirectory"
Write-Host "Set the environment variables documented in this script's own help (Get-Help $($MyInvocation.MyCommand.Path) -Full) before running the opt-in tests."
