<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(ThunderPropagatorPackageId)"/>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="AirportDemoChannelFeederMessage.cs">
            <DependentUpon>AirportDemoChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="AirportDemoChannelMetadata.cs">
            <DependentUpon>AirportDemoChannel.cs</DependentUpon>
        </Compile>
        <Compile Update="AirportDemoChannelFeederConfiguration.cs">
            <DependentUpon>AirportDemoChannelFeeder.cs</DependentUpon>
        </Compile>
        <Compile Update="Statuses.cs">
            <DependentUpon>AirportDemoChannelFeederMessage.cs</DependentUpon>
        </Compile>
        <Compile Update="AirportDemoChannelConfiguration.cs">
            <DependentUpon>AirportDemoChannel.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
